
security:
  user:
    name: root
    password: eureka

datasource:
  username: root
  password: root
  url: jdbc:mysql://127.0.0.1:3306/luck_product?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  driver-class-name: com.mysql.cj.jdbc.Driver

redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password: root
  timeout: PT1800S
  jedis:
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 100
      max-wait: -1
  expire: 7200

jdbc:
  type: mysql

ignore-urls:
  - "/login"
  - "/logout"

token:
  expired: 36000

