server:
  port: 9070
spring:
  application:
    name: luck-config
  profiles:
    # 使用本地配置
    active: native
  cloud:
    config:
      server:
        native:
          # 配置信息查询路径
          search-locations: classpath:/config/

eureka:
  client:
    service-url:
      defaultZone: http://root:eureka@localhost:9010/eureka/
  instance:
    prefer-ip-address: true
