server:
  port: 9090
  servlet:
    context-path: /
spring:
  application:
    name: luck-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
          # 路由ID
        - id: luck-system
          # 转发地址
          uri: http://localhost:9080
          # 匹配路径
          predicates:
            - Path=/sys/**
          # 去掉前缀
          filters:
            - StripPrefix=1

  redis:
    database: ${redis.database}
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    timeout: ${redis.timeout}
    jedis:
      pool:
        max-idle: ${redis.jedis.pool.max-idle}
        min-idle: ${redis.jedis.pool.min-idle}
        max-active: ${redis.jedis.pool.max-active}
        max-wait: ${redis.jedis.pool.max-wait}
    expire: ${redis.expire}

eureka:
  client:
    service-url:
      defaultZone: http://root:eureka@localhost:9010/eureka/
  instance:
    prefer-ip-address: true



