server:
  port: 9090
  servlet:
    context-path: /
spring:
  application:
    name: luck-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
          # 路由ID
        - id: luck-system
          # 转发地址
          uri: http://localhost:9080
          # 匹配路径
          predicates:
            - Path=/sys/**
          # 去掉前缀
          filters:
            - StripPrefix=1

  datasource:
    username: ${datasource.username}
    password: ${datasource.password}
    url: ${datasource.url}
    driver-class-name: ${datasource.driver-class-name}

  redis:
    database: ${redis.database}
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    timeout: ${redis.timeout}
    jedis:
      pool:
        max-idle: ${redis.jedis.pool.max-idle}
        min-idle: ${redis.jedis.pool.min-idle}
        max-active: ${redis.jedis.pool.max-active}
        max-wait: ${redis.jedis.pool.max-wait}
    expire: ${redis.expire}

mybatis-plus:
  typeAliasesPackage: com.luck.cloud.**.entity,com.luck.cloud.**.vo
  typeAliasesSuperType: com.luck.cloud.base.entity.BaseEntity
  mapper-locations: classpath*:mapper/${jdbc.type}/**/*.xml
  config-location: classpath:mybatis-config.xml
  global-config:
    db-config:
      idType: ASSIGN_ID


eureka:
  client:
    service-url:
      defaultZone: http://root:eureka@localhost:9010/eureka/
  instance:
    prefer-ip-address: true

jwt:
  token:
    expired: ${token.expired}

security:
  ignore:
    urls:
      - "/login"
      - "/logout"

